POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "test",
    "postType": "story",
    "slug": "/1234",
    "status": "draft",
    "content": "Once upon a time...",
    "schema": "A schema",
    "featuredImageUrl": "https://example.com/image.jpg",
    "publishedOn": "2022-10-01T00:00:00Z",
    "tags": ["tag1", "tag2"],
    "metaOptions": { "meta1": "some meta" }
}
