POST http://localhost:3000/posts
Content-Type: application/json

{   "title": "New with NestJS",
    "postType": "post",
    "slug": "new-with-nestjs",
    "status": "draft",
    "content": "Once upon a time...",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\",\r\n }",
    "featuredImageUrl": "https://example.com/image.jpg",
    "publishedOn": "2022-10-01T00:00:00Z",
    "tags": ["nestjs", "typescript"],
    "metaOptions": [{ "key": "testKey", "value": 20 }]
}
